# Lec 7-9: Array Programming Paradigm: The Basic


Jianwen Zhu <jzhu@eecg.toronto.edu>
v2.0, 2024-09


## Agenda
------

* Array Programming Paradigm
* NumPy
* Array as collection
* Elementwise operations
* Reduction


## Array Programming Language
--------------------------

* Native sequences are nice
 - But very general: element can be anything
 - Slow for large scale data and numerical computation
 
* Array Programming Paradigm
  - Everything is an array
  - No loops! (we already saw list comprehension)
  
* APL (A Programming Language)
  - Kenneth E. Iverson: Candian Computer Scientist
  - Turing Speech: "Notations as a Tool of Thoughts"
     (one of the most inspiring talks in CS)
  - Influenced spreadsheets, functional programming, and
    computer math packages

* Vector machine
  - Vector Machine
  - Each register is an array
  - Instructions operate on arrays
  - Seymour Cray: Father of Supercomputer

* Modern Incarnation
    - Tensor
    - From Descrete Objects to Tensor

* Question: How to
    - Combine performance of C
    - Expressive Power of APL
    - Python as a language substrate

* NumPy: Multidimensional arrays!
    - Vector / Matrix
    - Photos
    - Tensors



## NumPy Package
-------------

### Installing from Source (Really Ancient Way)
* Retrieving source

~~~
>wget url
~~~

* Unpack

~~~
>tar xvfz foo.tar.gz
~~~

* Installation
 - setup.py

~~~
>python setup.py build
>python setup.py install --user
~~~

* Ready to import

### Installing Using a Package Manager
~~~
%pip install numpy
~~~

Below code is a bit more cumbersome than usual. This is because
we want to install within the Jupyter Environment (the kernel
is running from a virtual environment, and we want to make
sure we are using the same python as the Jupter kernel.)

In [ ]:
import sys
!{sys.executable} -m pip install numpy

In [ ]:
import numpy as np

## NumPy Type: ndarray
-------------------

* Rank
    - Number of dimensions
 
* Axis
    - Each dimension

* Shape
    - tuple of integers indicating the size of the array in each dimension

* accessors
    - a.ndim: rank
    - a.shape: shape
    - a.size: total number of elements (prod of all elements of shape)
    - a.itemsize: number of bytes for each elements
    - a.dtype: data type of each element
    - a.data: actual data (do not use directly)

In [ ]:
from numpy  import *
a = arange(10).reshape(2,5)
a

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a.dtype

In [ ]:
a.itemsize

In [ ]:
a.size

## array Constructor function

### Convert from sequences


In [ ]:
import numpy as np
a = np.array( [2,3,4] )

In [ ]:
a

In [ ]:
a.dtype

In [ ]:
b = np.array([1.2, 3.5, 5.1])

In [ ]:
b.dtype

### Or sequences of sequences ...

In [ ]:
b = np.array( [ (1.5,2,3), (4,5,6) ] )
b

### zeros/ones/empty construction

In [ ]:
np.zeros( (3,4) )

In [ ]:
np.ones( (2,3,4), dtype=int16 ) 

In [ ]:
np.empty( (2,3) )

### arange

recall range function ?


In [ ]:
np.arange( 10, 30, 5 )

In [ ]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

### linspace

It is NOT always convenient to use arange as it cannot control the number of elements directly. But we have alternatives that can give predictable number of elements.

In [ ]:
np.linspace( 0, 2, 9 ) 

In [ ]:
pi = 3.14
x = np.linspace( 0, 2*pi, 100 )

In [ ]:
f = np.sin(x)
f

In [ ]:
import sys
!{sys.executable} -m pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt

plt.plot( x, f )

### random


In [ ]:
np.random.random((2,3))

## Changing Shape

* Ravel

In [ ]:
a = np.array([[ 7.,  5.,  9.,  3.],
       [ 7.,  2.,  7.,  8.],
       [ 6.,  8.,  3.,  2.]])
a.ravel() # flatten the array

In [ ]:
a.shape = (6, 2)
a

In [ ]:
b = a.transpose()
b

## resize
   - modify the array in place

In [ ]:
a.resize((2,6))

## reshape
  - returns another array with changed shape
  - -1 means the dimension is automatically calculated according to other
    dimensions

In [ ]:
a.reshape(3,-1)

## Enumeration
* Hierarchical

In [ ]:
b = np.array( [[ 1, 2, 3], [4, 5, 6]] )
for element in b : 
    print( element )

* Flat

In [ ]:
for element in b.flat :
    print( element )

## Indexing and Slicing

### Just like list

In [2]:
import numpy as np

a = np.array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
a[2]

8

In [3]:
a[2:5]

array([ 8, 27, 64])

In [4]:
a[:6:2]

array([ 0,  8, 64])

In [5]:
a[:6:2] = -1000   
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [6]:
a[::-1]     

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

### Tuple Indexed (NOT Like List)

In [7]:
b = np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [8]:
b[2,3]

23

In [9]:
b[:,1]     

array([ 1, 11, 21, 31, 41])

We are asking for ALL rows, and column 1, do shape analysis

Note that we have dimension reduction, just like a regular index. But we dont have to!

In [10]:
 b[1:3,:]  # row1/2, all columns

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

### Missing Indices

In [11]:
b[-1]            # the last row, do shape analysis again

array([40, 41, 42, 43])

* Dots (...)
  - Means: as many as :
  - x[1,2,...] is equivalent to x[1,2,:,:,:],
  - x[...,3] to x[:,:,:,:,3] and
  - x[4,...,5,:] to x[4,:,:,5,:].
  - Key of understanding: Shape Analysis in your brain (just like type analysis)

In [12]:
c = np.array( [ [[  0,  1,  2],               # a 3d array (two stacked 2d arrays)
           [ 10, 12, 13]],
           [[100,101,102],
           [110,112,113]] ] )

In [13]:
c.shape

(2, 2, 3)

In [18]:
c[:,0,:]

array([[  0,   1,   2],
       [100, 101, 102]])

In [19]:
c[1,...]   # matrix 1 (full)

array([[100, 101, 102],
       [110, 112, 113]])

In [15]:
c[...,2]  # taking colum 2 of all

array([[  2,  13],
       [102, 113]])

## Elementwise Functions

* So far similar to list
  - Seems just a convenience
  - Maybe more efficient in storage
  - But why bother?

  - compare

~~~
for i in range(len(a)) :
  c[i] = a[i] + b[i]
~~~

~~~
[ x + y for x, y in zip(a,b)]
~~~

But How about simply this!
~~~
a + b
~~~


* array op array
  - vector operation just like scalar operation
  - no loops
  - not even list comprehension


In [20]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print( b )
c = a-b
c

[0 1 2 3]


array([20, 29, 38, 47])

* array op scalar

In [21]:
b ** 2

array([0, 1, 4, 9])

In [22]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [23]:
print(a) 
a < 35

[20 30 40 50]


array([ True,  True, False, False])

## Univeral Functions

Recall "operators" like "+" are just plain, but "polymorphic" functions.
We can have more such functions, but with names. 

* Unary
    - arccos/arccosh/arcsin/arcsinh/arctan/arctanh
    - cos/cosh/exp/log/log10/sin/sinh/sqrt/tan/tanh
    - ...
    
* Binary
    - add/subtract/multiply/divide
    - remainder
    - power
    - ...

 - Comparison
   - greater/less
   - ...
   

## More Indexing and Slicing

* We saw indexing by
  - integers
  - slices
  - tuple of integers/slices

* Array of integers!
  - Gather operation

In [24]:
a = np.arange(12)**2                       # the first 12 square numbers
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices
print( a )
print( i )

[  0   1   4   9  16  25  36  49  64  81 100 121]
[1 1 3 8 5]


In [25]:
a[i]                                       

array([ 1,  1,  9, 64, 25])

In [27]:
palette = np.array( [ [0,0,0],                # black
                  [255,0,0],               # red
                    [0,255,0],              # green
                    [0,0,255],              # blue
                    [255,255,255] ] )       # white


In [28]:
image = np.array( [ [ 0, 1, 2, 0 ],           # 2x4 image with color index entry
                 [ 0, 3, 4, 0 ]  ] )


In [29]:
 palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

* Scatter operation
  

In [30]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [32]:
a = np.arange(5)
a[[0,0,2]]=[1,2,3]
a

array([2, 1, 3, 3, 4])

NOTE: For repeat entries, take the value of last one.

## Array of Booleans (Pack)

In [33]:
import numpy as np

a = np.arange(12).reshape(3,4)
print( a )
b = a > 4
b                                          # b is a boolean with a's shape


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
a[b]   # 1d array with the selected elements

array([ 5,  6,  7,  8,  9, 10, 11])

In [37]:
a[b] = 0     # All elements of 'a' higher than 4 become 0

In [38]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

Question: We have seen how elementwise operation help eliminate
loops in code -- what procedural construct does pack help eliminate? 

## Fractal Example

*  Mandelbrot set
    - Given a complex number z, make a copy of the number (call it c),
      and then perform the following operation recursively:

~~~      
    z = z**2 + c
~~~

* May go to infinity - Refinement:

  - Any point z which, after N (let's say 100) iterations, has a magnitude not exceeding a threshold (let's say 10), belongs to the Mandelbrot set.

  - The iteration that make z exceeding 10, defines the "escape speed"

* Visualization: We know that a complex number is a point in a two-demensinoal space, so it maps well to an image.

* Your challenge: Use as LITTLE control (imperative) statements as possible!


* We have already seen how to construct a 1D axis

In [ ]:
import numpy as np
print( np.linspace( 0, 1, num=5 ).dtype )

In [ ]:
re = np.linspace( -2.0, 1, 1000 )
im = np.linspace( -1.5, 1.5, 1000 )

Let's construct an 2D grid

In [ ]:
a, b = np.meshgrid( [1,2,3], [1,2] )
print( a )
print( b )

Repeat the first argument by the size of the second argument;
Repeat the second element by the size of the first argument, but rotated.
They are basically the horizontal and vertical grid lines.

In [ ]:
 x, y = np.meshgrid(re, im)

* Complex grid: What is happening below: 

In [ ]:
z = x + 1j*y
z.shape

This an ELEMENT-WISE operation applied on equal-shaped matrics. For every respective element in the matrix, we form a complex number. What have we done: We basically enumerated ALL complex points within a square range by a SINGLE expression!

In [ ]:
a = np.array( [1, 2, 3] )
b = a[:2]
print( b )
b[0] = 3         #numpy array is mutable
print( b )

In [ ]:
print( a )

What happend? Changing value of b also changes value of a? 

This is because b is just a "view" of a (implementation choice
by Numpy designer). To create an independent value, have to use
the "copy" method. 

In [ ]:
b = a[:2].copy()
b[0] = 3
print( b )
print( a )

In [ ]:
b = a[:2].copy()
b[0] = 3
print( b )
print( a )

Now let's get back to Mendalbrot Set problem. 

In [ ]:
c = z.copy()
for n in range( 100 ) :
    print( "Iteration %d" % n )
    z *= z
    z += c

Seem all trival and familiar expressions, but remember z is a GRID of scalar complex numbers, and we are performing on each one of them! 

NOTE: *= and += are *in place* operators, they are NOT euivalent to 
z = z * z, and z = z + c.

Now we need to use the DEFINITION of Mandelbrot set, and visualize it using an image.

In [ ]:
fractal = np.zeros(z.shape, dtype=np.uint8)

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(fractal, cmap='grey')
plt.plot()

This is just all dark, but it is OK as a pixel value is 0. Let's mark the points of Mendelbrot set white. Recall that for any point p in z which, after 100 iterations, has a magnitude (np.abs(p)) of greater than 10, belongs to the Mandelbrot set. Challenge you to get the image use ONE expression!

In [ ]:
z = x + 1j*y
c = z.copy()
for n in range( 100 ) :
    print( "Iteration %d" % n )
    z *= z
    z += c
fractal[np.abs(z) <= 10] = 255

In [ ]:
import matplotlib.pyplot as plt

plt.clf()
plt.imshow(fractal, cmap='grey')
plt.plot()

Let's put them all together, and with fancier graphics: we want to use pixel color to indicate the "escape speed", in other words, how soon they "escape" the set,
the earlier, the darker. We will also make the code slightly more general 
by making constants into "hyper-parameters" that can be changed for exploration.

In [ ]:
ITERATIONS = 100
DENSITY = 1000 # warning: execution speed decreases with square of DENSITY

x_min, x_max = -2, 1
y_min, y_max = -1.5, 1.5

x, y = np.meshgrid(np.linspace(x_min, x_max, DENSITY),
                   np.linspace(y_min, y_max, DENSITY))

c = x + 1j*y # complex grid
z = c.copy()
fractal = np.zeros(z.shape, dtype=np.uint8) + 255

for n in range(ITERATIONS):
    print( "Iteration %d" % n )

    # --- Uncomment to see different sets ---

    # Tricorn
    #z = z.conj()

    # Burning ship
    # z = abs(z.real) + 1j*abs(z.imag)

    # ---
    # Leave the lines below in place
    z *= z
    z += c

    # first time escape
    mask = (fractal == 255) & (abs(z) > 10)
    # assign with color/hot code
    fractal[mask] = 254 * n / float(ITERATIONS)

plt.imshow(np.log(fractal), cmap=plt.cm.hot,
           extent=(x_min, x_max, y_min, y_max))
plt.title('Mandelbrot Set')
plt.xlabel('Re(z)')
plt.ylabel('Im(z)')
plt.show()

Note we use different color map in imshow() function call. The color map basically turns pixel values into real RGB values (remember the palatte exampler earlier?). 

Also note that you can explore different variants of the Mandelbrot set by uncommenting some statements in the code. 

While the images are strickingly beautiful, it is more intriguring to see how the task is accomplished in a DIFFERENT language paradigm. 